import { Roboto} from 'next/font/google'; // Use Roboto instead of Geist
import './globals.css';

const roboto = Roboto({
  variable: '--font-roboto', // Define the variable for Roboto
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Add weights as needed
});

const robotoMono = Roboto ({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata = {
  title: 'Search Engine',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
